substitutions:
  name: pzem004
  friendly_name: pzem004

esphome:
  name: pzem004
  on_boot:
    then:
      - delay: 5s
      - pzemac.reset_energy: pzem004

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # baud_rate: 0 # 和 UART 冲突，关闭日志

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: "${friendly_name} Version"
    hide_timestamp: false
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
    mac_address:
      name: "${friendly_name} Mac Wifi Address"
    scan_results:
      name: "${friendly_name} Latest Scan Results"
    dns_address:
      name: "${friendly_name} DNS Address"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: "88888888"

captive_portal:

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 15s

  - platform: pzemac
    id: pzem004
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    energy:
      name: "${friendly_name} Energy"
    power:
      name: "${friendly_name} Power"
      id: pzem004_power
    frequency:
      name: "${friendly_name} Frequency"
    power_factor:
      name: "${friendly_name} Power Factor"
    update_interval: 15s

  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: pzem004_power
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:counter

  - platform: integration
    name: "${friendly_name} Energy Meter" 
    sensor: pzem004_power
    time_unit: h
    filters:
      # Multiplication factor from W to kW is 0.001
      - lambda: return x * (0.001) + 2350;
    unit_of_measurement: kWh
    icon: mdi:counter

  # 启动时间
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor
    update_interval: 5s

  # WiFi信号强度
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 5s

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

uart:
  rx_pin:
    number: GPIO16
  tx_pin:
    number: GPIO17
  baud_rate: 9600
  id: mod_uart

modbus:
  send_wait_time: 50ms
  uart_id: mod_uart
  id: mod_bus
