esphome:
  name: pzem004

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "myblue"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-Esp Fallback Hotspot"
    password: "gpBPJAAAAAnA"

captive_portal:
    
sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 15s

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

